name: Android CI

on:
  push:
    branches:
      - "main"
    paths:
      - "CHANGELOG.md"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-22.04  # Gunakan Ubuntu 22.04 bukan ubuntu-latest
    env:
      ver_name: "v1.0.0"
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    permissions:
      contents: write
      packages: write

    steps:
    - uses: actions/checkout@v4
    
    - name: Setup Android NDK
      uses: android-actions/setup-android-ndk@v1
      with:
        ndk-version: "25.1.8937393"  # Gunakan NDK version yang tersedia

    - name: Build with NDK
      run: |
        cd ${{ github.workspace }}/AndKittyInjector
        # Set environment variables untuk NDK
        export ANDROID_NDK_HOME=$ANDROID_NDK_ROOT
        sh ndk-build.sh
        
    - name: Package binaries
      run: |
        cd ${{github.workspace}}/AndKittyInjector/cmake_build
        mv arm64-v8a/AndKittyInjector AndKittyInjector-arm64-v8a
        mv armeabi-v7a/AndKittyInjector AndKittyInjector-armeabi-v7a
        mv x86_64/AndKittyInjector AndKittyInjector-x86_64
        mv x86/AndKittyInjector AndKittyInjector-x86
        gzip AndKittyInjector-arm64-v8a
        gzip AndKittyInjector-armeabi-v7a
        gzip AndKittyInjector-x86_64
        gzip AndKittyInjector-x86
        
    - name: Upload Artifacts
      uses: actions/upload-artifact@v4
      with:
        name: "gz"
        path: ${{ github.workspace }}/AndKittyInjector/cmake_build/*.gz

    - name: Create Release
      uses: softprops/action-gh-release@v0.1.15
      with:
        files: |
          ${{ github.workspace }}/AndKittyInjector/cmake_build/AndKittyInjector-arm64-v8a.gz
          ${{ github.workspace }}/AndKittyInjector/cmake_build/AndKittyInjector-armeabi-v7a.gz
          ${{ github.workspace }}/AndKittyInjector/cmake_build/AndKittyInjector-x86_64.gz
          ${{ github.workspace }}/AndKittyInjector/cmake_build/AndKittyInjector-x86.gz
        tag_name: v1.0.${{ github.run_number }}
        body_path: ${{ github.workspace }}/CHANGELOG.md
