name: Android CI

on:
  workflow_dispatch:
  push:
    branches: [ main ]


jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Download Command Line Tools
      run: |
          cd /home/runner/work/AndKittyInjector/AndKittyInjector/AndKittyInjector
          ls
          sh ndk-build.sh
          
