name: Android CI

on:
  workflow_dispatch:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Download Command Line Tools
      run: |
          
          TOOLS_URL="https://dl.google.com/android/repository/commandlinetools-linux-13114758_latest.zip"
          wget $TOOLS_URL -O cmdline-tools.zip
          unzip cmdline-tools.zip -d $ANDROID_HOME
          rm cmdline-tools.zip
          yes | /usr/local/lib/android/sdk/cmdline-tools/bin/sdkmanager --licenses
          /usr/local/lib/android/sdk/cmdline-tools/bin/sdkmanager "cmake;3.30.3"
