name: Android CI

on:
  push:
    branches:
      - "main"
    paths:
      - "CHANGELOG.md"
  workflow_dispatch:


jobs:
  build:

    runs-on: ubuntu-latest
    env:
      ver_name: "v1.0.0"
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    permissions: # 声明所需权限:ml-citation{ref="1" data="citationList"}
      contents: write    # 仓库内容写入权限（包含repo）
      packages: write    # 包管理写入权限

    steps:
    - uses: actions/checkout@v4

    - name: Download Command Line Tools
      run: |
          cd ${{ github.workspace }}/AndKittyInjector
          find /usr/local/lib/android/ -name make
          find /usr/local/lib/android/ -name cmake
          ls
          sh ndk-build.sh
    - name: Upload Release APK To Artifact
      uses: actions/upload-artifact@v4
      with:
        name: "arm64-v8a"
        path: ${{ github.workspace }}/AndKittyInjector/cmake_build/arm64-v8a/AndKittyInjector

    - uses: softprops/action-gh-release@v0.1.15
      with:
        name: ${{ env.ver_name }}
        tag_name: ${{ env.ver_name }}
        body_path: ${{ github.workspace }}/CHANGELOG.md
        draft: false
        prerelease: false
        files: ${{ github.workspace }}/AndKittyInjector/cmake_build/arm64-v8a/AndKittyInjector

          
