name: Android CI

on:
  push:
    branches:
      - "master"
    paths:
      - "CHANGELOG.md"
  workflow_dispatch:


jobs:
  build:

    runs-on: ubuntu-latest
    env:
      ver_name: "1.0.0"

    steps:
    - uses: actions/checkout@v4

    - name: Download Command Line Tools
      run: |
          cd /home/runner/work/AndKittyInjector/AndKittyInjector/AndKittyInjector
          find /usr/local/lib/android/ -name make
          find /usr/local/lib/android/ -name cmake
          ls
          sh ndk-build.sh
    - name: Upload Release APK To Artifact
      uses: actions/upload-artifact@v4
      with:
        name: "arm64-v8a"
        path: /home/runner/work/AndKittyInjector/AndKittyInjector/AndKittyInjector/cmake_build/arm64-v8a/AndKittyInjector

    - uses: softprops/action-gh-release@v0.1.15
      with:
        name: ${{ env.ver_name }}
        tag_name: ${{ env.ver_name }}
        body_path: ${{ github.workspace }}/CHANGELOG.md
        draft: false
        prerelease: false
        files: /home/runner/work/AndKittyInjector/AndKittyInjector/AndKittyInjector/cmake_build/arm64-v8a/AndKittyInjector
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          
