name: Android CI

on:
  push:
    branches:
      - "main"
    paths:
      - "CHANGELOG.md"
  workflow_dispatch:


jobs:
  build:
    runs-on: ubuntu-latest
    env:
      ver_name: "v1.0.0"
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    permissions: # 声明所需权限:ml-citation{ref="1" data="citationList"}
      contents: write    # 仓库内容写入权限（包含repo）
      packages: write    # 包管理写入权限

    steps:
    - uses: actions/checkout@v4

    - name: Download Command Line Tools
      run: |
          cd ${{ github.workspace }}/AndKittyInjector
          #find /usr/local/lib/android/ -name make
          #find /usr/local/lib/android/ -name cmake
          #ls
          sh ndk-build.sh
    - name: tar
      run: |
        cd ${{github.workspace}}/AndKittyInjector/cmake_build
        mv arm64-v8a/AndKittyInjector AndKittyInjector-arm64-v8a
        mv armeabi-v7a/AndKittyInjector AndKittyInjector-armeabi-v7a
        mv x86_64/AndKittyInjector AndKittyInjector-x86_64
        mv x86/AndKittyInjector AndKittyInjector-x86
        gzip AndKittyInjector-arm64-v8a
        gzip AndKittyInjector-armeabi-v7a
        gzip AndKittyInjector-x86_64
        gzip AndKittyInjector-x86
    - name: Download Artifacts
      uses: actions/upload-artifact@v4
      with:
        name: "gz"
        path: /home/runner/work/AndKittyInjector/AndKittyInjector/AndKittyInjector/cmake_build/*.gz  # 下载到统一目录



    - name: Create Release
      uses: softprops/action-gh-release@v0.1.15
      with:
        files: |
          ${{ github.workspace }}/AndKittyInjector/cmake_build/AndKittyInjector-arm64-v8a.gz
          ${{ github.workspace }}/AndKittyInjector/cmake_build/AndKittyInjector-armeabi-v7a.gz
          ${{ github.workspace }}/AndKittyInjector/cmake_build/AndKittyInjector-x86_64.gz
          ${{ github.workspace }}/AndKittyInjector/cmake_build/AndKittyInjector-x86.gz
        tag_name: v1.0.${{ github.run_number }}
        body_path: ${{ github.workspace }}/CHANGELOG.md