name: Android CI

on:
  workflow_dispatch:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Download Command Line Tools
      run: |
          $ANDROID_HOME/cmdline-tools/bin/sdkmanage1
          TOOLS_URL="https://dl.google.com/android/repository/commandlinetools-linux-13114758_latest.zip"
          wget $TOOLS_URL -O cmdline-tools.zip
          unzip -q cmdline-tools.zip -d $ANDROID_HOME
          rm cmdline-tools.zip
          
          yes | $ANDROID_HOME/cmdline-tools/bin/sdkmanager --licenses
          find ./ -name sdkmanager
          $ANDROID_HOME/cmdline-tools/bin/sdkmanager "cmake;3.30.3"
