name: Android CI

on:
  workflow_dispatch:
  push:
    branches: [ main ]


jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Download Command Line Tools
      run: |
          TOOLS_URL="https://dl.google.com/android/repository/commandlinetools-linux-13114758_latest.zip"
          wget -q $TOOLS_URL -O cmdline-tools.zip
          unzip -q cmdline-tools.zip -d $ANDROID_HOME/cmdline-tools
          rm cmdline-tools.zip
          mv $ANDROID_HOME/cmdline-tools/cmdline-tools $ANDROID_HOME/cmdline-tools/latest
          yes | /usr/local/lib/android/sdk/cmdline-tools/latest/bin/sdkmanager --licenses
          /usr/local/lib/android/sdk/cmdline-tools/latest/bin/sdkmanager "ndk;25.2.9519653"
          /usr/local/lib/android/sdk/cmdline-tools/latest/bin/sdkmanager "cmake;3.22.1"
          cd /home/runner/work/AndKittyInjector/AndKittyInjector
          echo 123$NDK_HOME
        /usr/local/lib/android/sdk/ndk/toolchains/llvm/prebuilt/linux-x86_64/bin/make

          
